services:
    spigot:
        image: itzg/minecraft-server:java21-graalvm
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            TYPE: "SPIGOT"
            LEVEL_TYPE: "FLAT"
            MODE: "CREATIVE"
            MODRINTH_PROJECTS: 1u6JkXh5
            SPIGET: 28140
        volumes:
            - ./data/spigot:/data/plugins