services:
    paper:
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            TYPE: "PAPER"
            LEVEL_TYPE: "FLAT"
            MODE: "CREATIVE"
        volumes:
            - ./data/paper:/data/plugins