services:
    paper:
        image: itzg/minecraft-server:java21-graalvm
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            TYPE: "PAPER"
            LEVEL_TYPE: "FLAT"
            MODE: "CREATIVE"
            MODRINTH_PROJECTS: 1u6JkXh5
            SPIGET: 28140
        volumes:
            - ./data/paper:/data/plugins