services:
    folia:
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            TYPE: "FOLIA"
            LEVEL_TYPE: "FLAT"
            MODE: "CREATIVE"
            SPIGET: 28140
        volumes:
            - ./data/folia:/data/plugins