services:
    spigot:
        image: itzg/minecraft-server
        tty: true
        stdin_open: true
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            TYPE: "SPIGOT"
            LEVEL_TYPE: "FLAT"
            MODE: "CREATIVE"
        volumes:
            - ./data/spigot:/data/plugins