services:
    server1:
        image: itzg/minecraft-server:java21-jdk 
        tty: true
        stdin_open: true
        privileged: true
        environment:
            EULA: "TRUE"
            TYPE: "PAPER"
            LEVEL_TYPE: "FLAT"
            MODE: "CREATIVE"
            ONLINE_MODE: "FALSE"
            # MODRINTH_PROJECTS: 1u6JkXh5
            SPIGET: 28140
            SKIP_SUDO: true
        volumes:
            - ./data/servers/server1:/data
    
    server2:
        image: itzg/minecraft-server:java21-jdk 
        tty: true
        stdin_open: true
        privileged: true
        environment:
            EULA: "TRUE"
            TYPE: "PAPER"
            LEVEL_TYPE: "FLAT"
            MODE: "CREATIVE"
            ONLINE_MODE: "FALSE"
            # MODRINTH_PROJECTS: 1u6JkXh5
            SPIGET: 28140
            SKIP_SUDO: true
        volumes:
            - ./data/servers/server2:/data
    
    velocity:
        image: itzg/bungeecord
        tty: true
        stdin_open: true
        ports:
            - "25565:25577"
        environment:
            TYPE: "VELOCITY"
            DEBUG: "false"
        volumes:
            - ./data/servers/velocity:/server
        