server_connect_timeout: 5000
enforce_secure_profile: false
remote_ping_cache: -1
forge_support: false
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: false
disabled_commands:
- disabledcommandhere
servers:
  FirstServer:
    motd: 'SGTMS Server One Proxy'
    address: localhost:25567
    restricted: false
  OtherServer:
    motd: 'SGTMS Server Two Proxy'
    address: localhost:25566
    restricted: false
listeners:
- query_port: 25565
  motd: 'SGTMS Proxy Test One'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - FirstServer
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 2
  tab_size: 2
  force_default_server: false
ip_forward: true
remote_ping_timeout: 5000
prevent_proxy_connections: false
groups:
  md_5:
  - admin
connection_throttle: 4000
stats: a40a42ec-0988-4e4f-915c-ca7c73c49db1
connection_throttle_limit: 3
log_pings: true
